-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     created_at  TIMESTAMPTZ DEFAULT NOW(),
-- 	updated_at TIMESTAMPTZ DEFAULT NOW(),
--     first_name VARCHAR(200) DEFAULT NULL,
-- 	last_name VARCHAR(200) DEFAULT NULL,
-- 	username VARCHAR(200) DEFAULT NULL,
-- 	email VARCHAR(200) DEFAULT NULL,
-- 	mobile VARCHAR(200) DEFAULT NULL,
-- 	phone VARCHAR(200) DEFAULT NULL,
-- 	address VARCHAR(200) DEFAULT NULL,
-- 	active BOOLEAN DEFAULT TRUE,
-- 	last_login  TIMESTAMPTZ DEFAULT NOW(),
-- 	last_password_change  TIMESTAMPTZ DEFAULT NOW(),
-- 	role_id INTEGER NULL DEFAULT 200,
--     company_id INTEGER NULL DEFAULT NULL,
-- 	location_id  INTEGER NULL DEFAULT NULL
-- )
CREATE TABLE public.users (
  	id SERIAL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    first_name text,
    last_name text,
    username text,
    password text,
    email text,
    mobile text,
    phone text,
    address text,
    active boolean,
    last_login timestamp with time zone DEFAULT now(),
    last_password_change timestamp with time zone DEFAULT now(),
    token text,
    role_id INTEGER,
    company_id INTEGER,
    location_id INTEGER
);
